spack:
  compilers::
  - compiler:
      spec: gcc@12.1.0
      paths:
        cc: /usr/bin/gcc-12
        cxx: /usr/bin/g++-12
        f77: /usr/bin/gfortran-12
        fc: /usr/bin/gfortran-12
      flags: 
        cflags: -pthread
        cxxflags: -pthread
      operating_system: ubuntu22.04
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []

  # Regular TPLs do not need views
  view: false

  packages:
    all:
      target: [ivybridge]
      compiler: [gcc]
      providers:
        blas: [openblas]
        lapack: [openblas]
        gl: [opengl]
        glu: [openglu]

    # Lock down versions of packages we depend on
    opengl:
      buildable: false
      externals:
      - spec: opengl@1.7.0
        prefix: /usr
    openglu:
      buildable: false
      externals:
      - spec: openglu@1.3.1
        prefix: /usr
    bzip2:
      buildable: false
      externals:
      - spec: bzip2@1.0.8
        prefix: /
    gettext:
      buildable: false
      externals:
      - spec: gettext@0.19.8.1
        prefix: /usr
    elfutils:
      buildable: false
      externals:
      - spec: elfutils@0.186
        prefix: /usr
    perl:
      buildable: false
      externals:
      - spec: perl@5.30.0
        prefix: /usr
    tar:
      buildable: false
      externals:
      - spec: tar@1.30
        prefix: /
    libx11:
      buildable: false
      externals:
      - spec: libx11@6.3.0
        prefix: /usr
    autoconf:
      buildable: false
      externals:
      - spec: autoconf@2.69
        prefix: /usr
    openssl:
      externals:
      - spec: openssl@1.1.1
        prefix: /usr/lib/x86_64-linux-gnu/
    openblas:
      buildable: false
      externals:
      - spec: openblas@0.3.8
        prefix: /usr/lib/x86_64-linux-gnu/
    pkg-config:
      buildable: false
      externals:
      - spec: pkg-config@0.29.2
        prefix: /usr
    unzip:
      buildable: false
      externals:
      - spec: unzip@6.0
        prefix: /usr
    zlib:
      buildable: false
      externals:
      - spec: zlib@1.2.11
        prefix: /usr
    cuda:
      buildable: false
      externals:
      - spec: cuda@12.1.0
        prefix: /usr/local/cuda
    m4:
      buildable: false
      externals:
      - spec: m4@1.4.16
        prefix: /usr
    hwloc:
      buildable: false
      externals:
      - spec: hwloc@2.7.0
        prefix: /usr
    numactl:
      buildable: false
      externals:
      - spec: numactl@2.0.14
        prefix: /usr
    openssh:
      buildable: false
      externals:
      - spec: openssh@8.9p1
        prefix: /usr

    # Lock in versions of Devtools
    cmake:
      buildable: false
      externals:
      - spec: cmake@3.20.4
        prefix: /usr
    cppcheck:
      version: [2.7]
      buildable: false
      externals:
      - spec: cppcheck@2.7
        prefix: /usr
    doxygen:
      version: [1.8.17]
      buildable: false
      externals:
      - spec: doxygen@1.8.17
        prefix: /usr
    llvm:
      version: [14.0.6]
      buildable: false
      externals:
      - spec: llvm@14.0.6+clang
        prefix: /usr
    python:
      version: [3.8.5]
      buildable: false
      externals:
      - spec: python@3.8.5
        prefix: /usr
    py-sphinx:
      version: [3.2.1]
      buildable: false
      externals:
      - spec: py-sphinx@3.2.1
        prefix: /usr
