FROM axom/compilers:ubuntu-20-gcc-9_07-06-21_11h-51m
LABEL maintainer="bramwell1@llnl.gov"
ARG branch=develop

SHELL ["/bin/bash", "-c"]
RUN sudo apt-get update -y
RUN sudo apt-get install ssh libopenblas-dev mpich gfortran -fy

RUN sudo useradd -m -s /bin/bash -G sudo serac

WORKDIR "/home/serac"
USER serac

RUN git clone --recursive --branch $branch --single-branch --depth 1 https://github.com/LLNL/serac.git

# New containers will use Python3
RUN cd serac && python3 ./scripts/uberenv/uberenv.py --spack-config-dir=./scripts/spack/configs/docker/ubuntu20/ \
                                                       --project-json=.uberenv_config.json \
                                                       --spec=%gcc@9.3.0 --prefix=/home/serac/serac_tpls -k
# white238: commented out due to logs disapearing and this being saved due to layering
#RUN rm -rf /home/serac/serac_tpls/builds

RUN mkdir -p /home/serac/export_hostconfig
RUN cp ./serac/*.cmake /home/serac/export_hostconfig

# Make sure the new hostconfig worked
RUN cd serac && python3 config-build.py -hc *.cmake -bp build && cd build && make -j && make -j test
RUN rm -rf serac
