FROM <IMAGE>
LABEL maintainer="bramwell1@llnl.gov"
ARG branch=develop

SHELL ["/bin/bash", "-c"]
RUN sudo apt-get update -y
RUN sudo apt-get install doxygen gettext gfortran graphviz libopenblas-dev libomp-dev libomp-15-dev lsb-release mpich python3-sphinx ssh texlive-full -fy

RUN sudo useradd -m -s /bin/bash -G sudo serac

WORKDIR "/home/serac"
USER serac

RUN git clone --recursive --branch $branch --single-branch --depth 1 https://github.com/LLNL/serac.git serac_repo

# Build/install TPLs via spack and then remove the temporary build directory on success
RUN cd serac_repo && python3 ./scripts/uberenv/uberenv.py --spack-env-file=./scripts/spack/configs/docker/ubuntu22/spack.yaml \
                                                          --project-json=.uberenv_config.json \
                                                          --spec=%<NAME>@<VER> --prefix=/home/serac/serac_tpls -k \
                  && rm -rf /home/serac/serac_tpls/builds

RUN mkdir -p /home/serac/export_hostconfig
RUN cp ./serac_repo/*.cmake /home/serac/export_hostconfig

# Make sure the new hostconfig worked
# Note: having high job slots causes build log to disappear and job to fail
RUN cd serac_repo && python3 config-build.py -hc *.cmake -bp build && cd build && make -j4 && make -j4 test && cd /home/serac && rm -rf serac_repo
