FROM ghcr.io/llnl/radiuss:clang-14-ubuntu-22.04
LABEL maintainer="bramwell1@llnl.gov"
ARG branch=develop

SHELL ["/bin/bash", "-c"]
RUN sudo apt-get update -y
RUN sudo apt-get install gettext gfortran-$(gcc -dumpversion) graphviz libomp-14-dev libopenblas-dev \
                         lsb-release lua5.2 lua5.2-dev mpich python3-sphinx ssh texlive-full -fy
RUN sudo useradd -m -s /bin/bash -G sudo serac

# Install proper doxygen version (should match version in LC host configs)
RUN sudo wget https://github.com/doxygen/doxygen/releases/download/Release_1_9_8/doxygen-1.9.8.linux.bin.tar.gz
RUN sudo tar -xf doxygen-1.9.8.linux.bin.tar.gz
RUN cd doxygen-1.9.8 && sudo make && sudo make install && doxygen --version

# Remove flags from mpich
RUN sudo sed -i "s/ -flto=auto//g" /usr/bin/mpicxx.mpich
RUN sudo sed -i "s/ -flto=auto//g" /usr/bin/mpicc.mpich
RUN sudo sed -i "s/ -flto=auto//g" /usr/bin/mpifort.mpich
RUN sudo sed -i "s/ -ffat-lto-objects//g" /usr/bin/mpicxx.mpich
RUN sudo sed -i "s/ -ffat-lto-objects//g" /usr/bin/mpicc.mpich
RUN sudo sed -i "s/ -ffat-lto-objects//g" /usr/bin/mpifort.mpich
RUN sudo sed -i "s/ -fallow-invalid-boz//g" /usr/bin/mpifort.mpich
RUN sudo sed -i "s/ -fallow-argument-mismatch//g" /usr/bin/mpifort.mpich

WORKDIR "/home/serac"
USER serac

RUN git clone --recursive --branch $branch --single-branch --depth 1 https://github.com/LLNL/serac.git serac_repo

# Build/install TPLs via spack and then remove the temporary build directory on success
RUN cd serac_repo && python3 ./scripts/uberenv/uberenv.py --spack-env-file=./scripts/spack/configs/docker/ubuntu22/spack.yaml \
                                                          --project-json=.uberenv_config.json \
                                                          --spec="%clang@14.0.0+shared" --prefix=/home/serac/serac_tpls -k \
                  && rm -rf /home/serac/serac_tpls/build_stage /home/serac/serac_tpls/spack

RUN mkdir -p /home/serac/export_hostconfig
RUN cp ./serac_repo/*.cmake /home/serac/export_hostconfig

# Make sure the new hostconfig worked
# Note: having high job slots causes build log to disappear and job to fail
RUN cd serac_repo && python3 config-build.py -hc *.cmake -bp build -DBUILD_SHARED_LIBS=ON && cd build && make -j4 VERBOSE=1 && make -j4 test && cd /home/serac && rm -rf serac_repo
