FROM axom/compilers:clang-6
LABEL maintainer="bramwell1@llnl.gov"
ARG branch=develop

RUN sudo apt-get update -y
RUN sudo apt-get install curl ssh pkg-config build-essential libopenblas-dev -fy
RUN sudo apt-get -qq install -y --no-install-recommends gfortran-7 && sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-7 100

#(For Clang Builds - Need to restore stdc++ lib)
RUN sudo apt-get install libstdc++-7-dev

RUN sudo useradd -m -s /bin/bash -G sudo serac

WORKDIR "/home/serac"
USER serac

RUN git clone --recursive https://github.com/LLNL/serac.git
RUN cd serac && git checkout $branch && cd ..

RUN ./serac/scripts/uberenv/uberenv.py --spack-config-dir=./serac/scripts/uberenv/spack_configs/docker/ubuntu16/ --spec=%clang@6.0.0 --prefix=/home/serac/serac_tpls -k

RUN mkdir -p /home/serac/export_hostconfig
RUN cp ./serac/*.cmake /home/serac/export_hostconfig

RUN rm -rf serac
