FROM axom/compilers:clang-10
LABEL maintainer="bramwell1@llnl.gov"
ARG branch=develop

RUN sudo apt-get update -y
RUN sudo apt-get install curl ssh pkg-config build-essential libopenblas-dev mpich -fy
RUN sudo apt-get -qq install -y --no-install-recommends gfortran-7 && sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-7 100
RUN sudo ln -s python3 /usr/bin/python # Compatibility with legacy Python

RUN sudo useradd -m -s /bin/bash -G sudo serac

WORKDIR "/home/serac"
USER serac

RUN git clone --recursive https://github.com/LLNL/serac.git
RUN cd serac && git checkout $branch && cd ..

# New containers will use Python3
RUN python3 ./serac/scripts/uberenv/uberenv.py --spack-config-dir=./serac/scripts/uberenv/spack_configs/docker/ubuntu18/ --spec=%clang@10.0.0 --prefix=/home/serac/serac_tpls -k

RUN mkdir -p /home/serac/export_hostconfig
RUN cp ./serac/*.cmake /home/serac/export_hostconfig

RUN rm -rf serac
RUN rm -rf serac_tpls/builds
