compilers:
  - compiler:
      environment: {}
      extra_rpaths: []
      # Axom example sidre_shocktube_F_ex doesn't link otherwise
      flags:
        cflags: -fPIC
        cppflags: -fPIC
      modules: []
      operating_system: ubuntu18.04
      paths:
        cc: /usr/bin/clang
        cxx: /usr/bin/clang++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      spec: clang@10.0.0
      target: x86_64
