# -------------------------------------------------------------------------
# This file controls default concretization preferences for Spack.
#
# Settings here are versioned with Spack and are intended to provide
# sensible defaults out of the box. Spack maintainers should edit this
# file to keep it current.
#
# Users can override these settings by editing the following files.
#
# Per-spack-instance settings (overrides defaults):
#   $SPACK_ROOT/etc/spack/packages.yaml
#
# Per-user settings (overrides default and site settings):
#   ~/.spack/packages.yaml
# -------------------------------------------------------------------------
packages:
  all:
    # This defaults us to machine specific flags of ivybridge which allows
    # us to run on broadwell as well
    target: [ivybridge]
    compiler: [gcc, intel, pgi, clang, xl, nag]
    providers:
      awk: [gawk]
      blas: [openblas]
      lapack: [openblas]
      daal: [intel-daal]
      elf: [elfutils]
      golang: [gcc]
      ipp: [intel-ipp]
      java: [jdk]
      mkl: [intel-mkl]
      mpe: [mpe2]
      mpi: [mpich]
      opencl: [pocl]
      openfoam: [openfoam-com, openfoam-org, foam-extend]
      pil: [py-pillow]
      scalapack: [netlib-scalapack]
      szip: [libszip, libaec]
      tbb: [intel-tbb]
      jpeg: [libjpeg-turbo, libjpeg]

  # Spack may grab for mpi & we don't want to use them
  mpi:
    buildable: false
  mpich:
    externals:
    - spec: mpich@3.3
      prefix: /usr

  # System level packages to not build
  autotools:
    buildable: false
    externals:
    - spec: autotools@2.69
      prefix: /usr
  bzip2:
    buildable: false
    externals:
    - spec: bzip2@1.0.6
      prefix: /usr
  gettext:
    buildable: false
    externals:
    - spec: gettext@0.19.8.1
      prefix: /usr
  m4:
    buildable: false
    externals:
    - spec: m4@1.4.18
      prefix: /usr
  perl:
    buildable: false
    externals:
    - spec: perl@5.26.1
      prefix: /usr
  pkg-config:
    buildable: false
    externals:
    - spec: pkg-config@0.29.1
      prefix: /usr
  tar:
    buildable: false
    externals:
    - spec: tar@1.29
      prefix: /usr
  graphviz:
    buildable: false
    externals:
    - spec: graphviz@2.40.1
      prefix: /usr
  openblas:
    buildable: false
    externals:
    - spec: openblas@0.2.20
      prefix: /usr

  # Globally lock in version of CMake
  cmake:
    version: [3.18.5]
    buildable: false
    externals:
    - spec: cmake@3.18.5
      prefix: /usr
  llvm:
    version: [10.0.0]
    buildable: false
    externals:
    - spec: llvm@10.0.0+clang
      prefix: /usr

  # Devtools
  cppcheck:
    version: [1.82]
    buildable: false
    externals:
    - spec: cppcheck@1.82
      prefix: /usr
  doxygen:
    version: [1.8.13]
    buildable: false
    externals:
    - spec: doxygen@1.8.13
      prefix: /usr
  python:
    version: [3.6.5]
    buildable: false
    externals:
    - spec: python@3.6.5
      prefix: /usr
  py-sphinx:
    version: [4.0.2]
    buildable: false
    externals:
    - spec: py-sphinx@4.0.2
      prefix: /usr
