# -------------------------------------------------------------------------
# This file controls default concretization preferences for Spack.
#
# Settings here are versioned with Spack and are intended to provide
# sensible defaults out of the box. Spack maintainers should edit this
# file to keep it current.
#
# Users can override these settings by editing the following files.
#
# Per-spack-instance settings (overrides defaults):
#   $SPACK_ROOT/etc/spack/packages.yaml
#
# Per-user settings (overrides default and site settings):
#   ~/.spack/packages.yaml
# -------------------------------------------------------------------------
packages:
  all:
    compiler: [gcc]
    providers:
      blas: [netlib-lapack]
      lapack: [netlib-lapack]
      mpi: [spectrum-mpi]
  cuda:
    buildable: false

  # LLNL blueos mpi
  mpi:
    buildable: false
  spectrum-mpi:
    externals:
      - spec: spectrum-mpi@release%clang@upstream_gfortran
        prefix: /usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-gcc-8.3.1

  # blas is a bit more complicated because its a virtual package so fake it with
  # the following per spack docs
  netlib-lapack:
    buildable: false
    externals:
    - spec: netlib-lapack@3.6.1
      prefix: /usr

  # System level packages to not build
  autoconf:
    buildable: false
    externals:
    - spec: autoconf
      prefix: /usr
  automake:
    buildable: false
    externals:
    - spec: automake
      prefix: /usr
  bzip2:
    buildable: false
    externals:
    - spec: bzip2
      prefix: /usr
  gettext:
    buildable: false
    externals:
    - spec: gettext
      prefix: /usr
  libtool:
    buildable: false
    externals:
    - spec: libtool
      prefix: /usr
  m4:
    buildable: false
    externals:
    - spec: m4
      prefix: /usr
  perl:
    buildable: false
    externals:
    - spec: perl
      prefix: /usr
  pkg-config:
    buildable: false
    externals:
    - spec: pkg-config
      prefix: /usr
  tar:
    buildable: false
    externals:
    - spec: tar
      prefix: /usr

  # Lock in versions of Devtools
  cmake:
    version: [3.14.5]
    buildable: false
    externals:
    - spec: cmake
      prefix: /usr/tce/packages/cmake/cmake-3.14.5
  llvm:
    version: [10.0.0]
    buildable: false
    externals:
    - spec: llvm+clang
      prefix: /usr/tce/packages/clang/clang-10.0.0
  python:
    version: [3.8.2]
    buildable: false
    externals:
    - spec: python@3.8.2
      prefix: /usr/tce/packages/python/python-3.8.2/
  py-sphinx:
    version: [2.2.0]
    buildable: false
    externals:
    - spec: py-sphinx@2.2.0
      prefix: /usr/tce/packages/python/python-3.8.2/
