# Globally lock version of third party libraries
packages:
  axom:
    require:
    - spec: "@0.14.0.2"
  adiak:
    require:
    - spec: "@0.4.1"
  caliper:
    require:
    - spec: "@2.15.0"
  camp:
    require:
    - spec: "@2025.12.0"
  conduit:
    require:
    - spec: "@0.9.6"
  # Hypre v3 causes equationsolver to fail TOSS 4
  hypre:
    require:
    - spec: "@2.33.0"
  mfem:
    require:
    - spec: "@4.10.0.1"
  petsc:
    require:
    - spec: "@3.23.7"
  raja:
    require:
    - spec: "@2025.12.2"
  sundials:
    require:
    - spec: "@7.7.0"
  tribol:
    require:
    - spec: "@0.1.0.28"
  umpire:
    require:
    - spec: "@2025.12.0"
