
spack:
  # add package specs to the `specs` list
  view: true
  concretizer:
    unify: true
  packages:
    all:
      compiler: [clang, gcc]
      providers:
        blas: [netlib-lapack]
        lapack: [netlib-lapack]
        mpi: [openmpi]
    mpi:
      buildable: false
    openmpi:
      buildable: false
      externals:
      - spec: openmpi@5.0.3_1
        prefix: /opt/homebrew
    netlib-lapack:
      buildable: false
      externals:
      - spec: netlib-lapack@3.12.0
        prefix: /opt/homebrew/opt/lapack
    autoconf:
      buildable: false
      externals:
      - spec: autoconf@2.72
        prefix: /opt/homebrew
    automake:
      buildable: false
      externals:
      - spec: automake@1.16.5
        prefix: /opt/homebrew
    bzip2:
      buildable: false
      externals:
      - spec: bzip2@1.0.8
        prefix: /opt/homebrew/opt/bzip2
    cmake:
      version: [3.29.6]
      buildable: false
      externals:
      - spec: cmake@3.29.5
        prefix: /opt/homebrew
    gettext:
      buildable: false
      externals:
      - spec: gettext@0.22.5
        prefix: /opt/homebrew
    graphviz:
      buildable: false
      externals:
      - spec: graphviz@11.0.0
        prefix: /opt/homebrew
    libtool:
      buildable: false
      externals:
      - spec: libtool@2.4.7
        prefix: /opt/homebrew
    libx11:
      buildable: false
      externals:
      - spec: libx11@1.8.9
        prefix: /opt/homebrew
    llvm:
      version: [18.1.8]
      buildable: false
      externals:
      - spec: llvm+clang@18.1.8
        prefix: /opt/homebrew/opt/llvm
    m4:
      buildable: false
      externals:
      - spec: m4@1.4.19
        prefix: /opt/homebrew/opt/m4
    perl:
      buildable: false
      externals:
      - spec: perl@5.34.1~cpanm+opcode+open+shared+threads
        prefix: /usr
    pkg-config:
      buildable: false
      externals:
      - spec: pkg-config@0.29.2_3
        prefix: /opt/homebrew
    python:
      buildable: false
      externals:
      - spec: python@3.12.4+bz2+crypt+ctypes+dbm+lzma+nis+pyexpat~pythoncmd+readline+sqlite3+ssl~tkinter+uuid+zlib
        prefix: /opt/homebrew/opt/python
    tar:
      buildable: false
      externals:
      - spec: tar@3.5.3
        prefix: /usr
    readline:
      buildable: false
      externals:
      - spec: readline@8.2.10
        prefix: /opt/homebrew
    unzip:
      buildable: false
      externals:
      - spec: unzip@6.0
        prefix: /usr
    zlib:
      buildable: false
      externals:
      - spec: zlib@1.3.1
        prefix: /opt/homebrew

 # The "::" removes all found/known compilers from Spack except for these.
  compilers::
  - compiler:
      spec: clang@=18.1.8
      paths:
        cc: /opt/homebrew/opt/llvm/bin/clang
        cxx: /opt/homebrew/opt/llvm/bin/clang++
        f77: /opt/homebrew/bin/gfortran-14
        fc: /opt/homebrew/bin/gfortran-14
      flags: {}
      operating_system: sonoma
      target: aarch64
      modules: []
      environment: {}
      extra_rpaths:
      - /opt/homebrew/lib/gcc/14
