spack:
  config:
    install_tree:
      root: $spack/..
      projections:
        all: '{compiler.name}-{compiler.version}/{name}-{version}-{hash}'
    misc_cache: $spack/../misc_cache
    test_stage: $spack/../test_stage
    build_stage::
    - $spack/../build_stage

  compilers::
  - compiler:
      environment: {}
      extra_rpaths: []
      # Axom example sidre_shocktube_F_ex doesn't link otherwise
      flags:
        cflags: -fPIC -pthread
        cxxflags: -fPIC -pthread
      modules: []
      operating_system: ubuntu22.04
      paths:
        cc: /usr/bin/clang
        cxx: /usr/bin/clang++
        f77: /usr/bin/gfortran-11
        fc: /usr/bin/gfortran-11
      spec: clang@14.0.0
      target: x86_64
  - compiler:
      environment: {}
      extra_rpaths: []
      flags:
        cflags: -pthread
        cxxflags: -pthread
      modules: []
      operating_system: ubuntu22.04
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran-13
        fc: /usr/bin/gfortran-13
      spec: gcc@13.1.0
      target: x86_64

  # Regular TPLs do not need views
  view: false

  packages:
    all:
      target: [x86_64]
      compiler: [gcc, intel, pgi, clang, xl, nag]
      providers:
        awk: [gawk]
        blas: [openblas]
        lapack: [openblas]
        daal: [intel-daal]
        elf: [elfutils]
        golang: [gcc]
        ipp: [intel-ipp]
        java: [jdk]
        mkl: [intel-mkl]
        mpe: [mpe2]
        mpi: [mpich]
        opencl: [pocl]
        openfoam: [openfoam-com, openfoam-org, foam-extend]
        pil: [py-pillow]
        scalapack: [netlib-scalapack]
        szip: [libszip, libaec]
        tbb: [intel-tbb]
        jpeg: [libjpeg-turbo, libjpeg]

    # Spack may grab for mpi & we don't want to use them
    mpi:
      buildable: false
    mpich:
      externals:
      - spec: mpich@4.0
        prefix: /usr

    # System level packages to not build
    autotools:
      buildable: false
      externals:
      - spec: autotools@20220109.1
        prefix: /usr
    bzip2:
      buildable: false
      externals:
      - spec: bzip2@1.0.8
        prefix: /usr
    curl:
      buildable: false
      externals:
      - spec: curl@7.81.0
        prefix: /usr
    gettext:
      buildable: false
      externals:
      - spec: gettext@0.21
        prefix: /usr
    lua:
      buildable: false
      externals:
      - spec: lua@5.2.4
        prefix: /usr
    m4:
      buildable: false
      externals:
      - spec: m4@1.4.18
        prefix: /usr
    perl:
      buildable: false
      externals:
      - spec: perl@5.34.0
        prefix: /usr
    pkg-config:
      buildable: false
      externals:
      - spec: pkg-config@0.29.2
        prefix: /usr
    tar:
      buildable: false
      externals:
      - spec: tar@1.34
        prefix: /usr
    graphviz:
      buildable: false
      externals:
      - spec: graphviz@2.42.2
        prefix: /usr
    openblas:
      buildable: false
      externals:
      - spec: openblas@0.3.20
        prefix: /usr

    # Globally lock in version of CMake
    cmake:
      version: [3.23.1]
      buildable: false
      externals:
      - spec: cmake@3.23.1
        prefix: /usr/local
    doxygen:
      version: [1.9.1]
      buildable: false
      externals:
      - spec: doxygen@1.9.1
        prefix: /usr
    llvm:
      version: [14.0.0]
      buildable: false
      externals:
      - spec: llvm@14.0.0+clang
        prefix: /usr
    py-sphinx:
      version: [4.3.2]
      buildable: false
      externals:
      - spec: py-sphinx@4.3.2
        prefix: /usr
