spack:
  config:
    install_tree:
      root: $spack/..
      projections:
        all: '{compiler.name}-{compiler.version}/{name}-{version}-{hash}'
    misc_cache: $spack/../misc_cache
    test_stage: $spack/../test_stage
    build_stage::
    - $spack/../build_stage

  # Regular TPLs do not need views
  view: false

  compilers::
  - compiler:
      environment: {}
      extra_rpaths: []
      flags:
        # Required as spack cannot recognize compiler-specific linker
        # flags in mixed toolchains
        ldlibs: -lgfortran
      modules: []
      operating_system: rhel7
      paths:
        cc:  /usr/tce/packages/clang/clang-ibm-10.0.1-gcc-8.3.1/bin/clang
        cxx: /usr/tce/packages/clang/clang-ibm-10.0.1-gcc-8.3.1/bin/clang++
        f77: /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
        fc:  /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
      spec: clang@10.0.1
      target: ppc64le

  packages:
    all:
      compiler: [gcc, intel, pgi, clang, xl, nag]
      providers:
        awk: [gawk]
        blas: [netlib-lapack]
        daal: [intel-daal]
        elf: [elfutils]
        golang: [gcc]
        ipp: [intel-ipp]
        java: [jdk]
        lapack: [netlib-lapack]
        mkl: [intel-mkl]
        mpe: [mpe2]
        # IBM Spectrum MPI is the only supported MPI 
        # library on LC's Sierra and CORAL EA systems.
        mpi: [spectrum-mpi]
        opencl: [pocl]
        openfoam: [openfoam-com, openfoam-org, foam-extend]
        pil: [py-pillow]
        scalapack: [netlib-scalapack]
        szip: [libszip, libaec]
        tbb: [intel-tbb]
        jpeg: [libjpeg-turbo, libjpeg]
        zlib-api: [zlib]
    py-numpy:
      variants: ~blas~lapack

    # LLNL blueos CUDA
    cuda:
      externals:
        - spec: cuda@11.2.0
          prefix: /usr/tce/packages/cuda/cuda-11.2.0
      buildable: false

    # LLNL blueos mpi
    mpi:
      buildable: false
    spectrum-mpi:
      externals:
        - spec: spectrum-mpi@release%clang@10.0.1
          prefix: /usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-clang-10.0.1-gcc-8.3.1

    netlib-lapack:
      externals:
        # This is the one that has the trailing underscores in name mangling, needed for MFEM compat
        - spec: netlib-lapack@3.9.0
          prefix: /usr/tcetmp/packages/lapack/lapack-3.9.0-gcc-7.3.1/lib/
      buildable: false

    # System level packages to not build
    autoconf:
      buildable: false 
      externals:
        - spec: autoconf@2.69
          prefix: /usr
    automake:
      buildable: false 
      externals:
        - spec: automake@1.13.4
          prefix: /usr
    binutils:
      buildable: false
      externals:
      - spec: binutils@2.27
        prefix: /usr
    bzip2:
      buildable: false
      externals:
      - spec: bzip2@1.0.6
        prefix: /usr
    curl:
      buildable: false
      externals:
      - spec: curl@7.29.0
        prefix: /usr
    diffutils:
      buildable: false
      externals:
      - spec: diffutils@3.3
        prefix: /usr
    elfutils:
      buildable: false
      externals:
      - spec: elfutils@0.176
        prefix: /usr
    findutils:
      buildable: false
      externals:
      - spec: findutils@4.5.11
        prefix: /usr
    gettext:
      buildable: false 
      externals:
        - spec: gettext@0.19.8.1
          prefix: /usr
    ghostscript:
      buildable: false
      externals:
      - spec: ghostscript@9.25
        prefix: /usr
    groff:
      buildable: false
      externals:
      - spec: groff@1.22.2
        prefix: /usr
    libepoxy:
      buildable: false
      externals:
      - spec: libepoxy@1.5.2
        prefix: /usr
    libtool:
      buildable: false
      externals:
      - spec: libtool@2.4.2
        prefix: /usr
    libunwind:
      buildable: false
      externals:
      - spec: libunwind@8.0.1
        prefix: /usr
    m4:
      buildable: false
      externals:
      - spec: m4@1.4.16
        prefix: /usr
    perl:
      buildable: false
      externals:
      - spec: perl@5.16.3
        prefix: /usr
    pkg-config:
      buildable: false
      externals:
      - spec: pkg-config@0.27.1
        prefix: /usr
    readline:
      buildable: false
      externals:
      - spec: readline@6.2
        prefix: /usr
    tar:
      externals:
        - spec: tar@1.26
          prefix: /usr
      buildable: false
    unzip:
      buildable: false
      externals:
      - spec: unzip@6.0
        prefix: /usr
    zlib:
      buildable: false
      externals:
      - spec: zlib@1.2.7
        prefix: /usr

    # Lock in versions of Devtools
    cmake:
      version: [3.23.1]
      buildable: false
      externals:
      - spec: cmake@3.23.1
        prefix: /usr/tce/packages/cmake/cmake-3.23.1
    cppcheck:
      version: [2.9]
      externals:
        - spec: cppcheck@2.9
          prefix: /usr/workspace/smithdev/devtools/blueos_3_ppc64le_ib_p9/latest/cppcheck-2.9
      buildable: false
    doxygen:
      version: [1.9.6]
      externals:
        - spec: doxygen@1.9.6
          prefix: /usr/workspace/smithdev/devtools/blueos_3_ppc64le_ib_p9/latest/doxygen-1.9.6
      buildable: false
    llvm:
      version: [10.0.0]
      buildable: false
      externals:
      - spec: llvm+clang@10.0.0
        prefix: /usr/tce/packages/clang/clang-10.0.0
    py-ats:
      version: [7.0.105]
      externals:
        - spec: py-ats@7.0.105
          prefix: /usr/workspace/smithdev/devtools/blueos_3_ppc64le_ib_p9/latest/python-3.10.10
      buildable: false
    py-sphinx:
      version: [7.0.0]
      externals:
        - spec: py-sphinx@7.0.0
          prefix: /usr/workspace/smithdev/devtools/blueos_3_ppc64le_ib_p9/latest/python-3.10.10
      buildable: false
    python:
      version: [3.8.2]
      externals:
        - spec: python@3.8.2~dbm
          prefix: /usr/tce/packages/python/python-3.8.2/
      buildable: false

    # Globally lock version of third party libraries
    camp:
      require: "@2023.06.0"
    conduit:
      require: "@0.8.8~shared~test~examples~utilities"
    hdf5:
      variants: ~shared~mpi
    raja:
      require: "@2023.06.1~shared~examples~exercises"
    umpire:
      require: "@2023.06.0~shared~examples"
