packages:
  all:
    compiler: [gcc]
    providers:
      mpi: [mpich]
      blas: [openblas]
      lapack: [openblas]
      gl: [opengl]
      glu: [openglu]

  # Lock down which MPI we are using
  mpi:
    buildable: false
  mpich:
    externals:
    - spec: mpich@3.3.2%gcc@9.3.0
      prefix: /usr

  # Lock down versions of packages we depend on
  opengl:
    buildable: false
    externals:
    - spec: opengl@1.7.0
      prefix: /usr
  openglu:
    buildable: false
    externals:
    - spec: openglu@1.3.1
      prefix: /usr
  bzip2:
    buildable: false
    externals:
    - spec: bzip2
      prefix: /
  gettext:
    buildable: false
    externals:
    - spec: gettext
      prefix: /usr
  perl:
    buildable: false
    externals:
    - spec: perl
      prefix: /usr
  tar:
    buildable: false
    externals:
    - spec: tar
      prefix: /
  libx11:
    buildable: false
    externals:
    - spec: libx11
      prefix: /usr
  autoconf:
    buildable: false
    externals:
    - spec: autoconf
      prefix: /usr
  openssl:
    externals:
    - spec: openssl
      prefix: /usr/lib/x86_64-linux-gnu/
  openblas:
    buildable: false
    externals:
    - spec: openblas
      prefix: /usr/lib/x86_64-linux-gnu/
  zlib:
    buildable: false
    externals:
    - spec: zlib
      prefix: /usr

  # Lock in versions of Devtools
  cmake:
    buildable: false
    externals:
    - spec: cmake@3.16.3
      prefix: /usr
  cppcheck:
    version: [1.9]
    buildable: false
    externals:
    - spec: cppcheck
      prefix: /usr
  doxygen:
    version: [1.8.17]
    buildable: false
    externals:
    - spec: doxygen
      prefix: /usr
  llvm:
    version: [10.0.0]
    buildable: false
    externals:
    - spec: llvm+clang
      prefix: /usr
  python:
    version: [3.8.2]
    buildable: false
    externals:
    - spec: python
      prefix: /usr
  py-sphinx:
    version: [1.8.5]
    buildable: false
    externals:
    - spec: py-sphinx
      prefix: /usr
